### ISSUE TITLE
Error on Overview page..

### ISSUE THREAD

**Issue by arg11** [gugoan/economizzer#118]
Hi,

It seems I am getting the error below; everything else seems fine, would you know what it is?

Database Exception – yii\db\Exception
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'economizzer.y.hexcolor_category' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
The SQL being executed was: SELECT x.`year`, x.`month`, y.desc_category as seg, y.hexcolor_category as colorseg, sum( x.value) as total FROM (
SELECT category.id_category, category.desc_category, category.parent_id , c.value AS value,
year(c.`date`) as `year` , month(c.`date`) AS `month`
FROM category
INNER JOIN cashbook AS c ON category.id_category = c.category_id ) AS x
INNER JOIN category AS y ON x.parent_id = y.id_category
INNER JOIN user AS u ON y.user_id = u.id
WHERE u.id = 3
GROUP BY y.desc_category, x.`year`, x.`month`
having x.`year` = year(now()) and x.`month` = month(now())

Error Info: Array
(
    [0] => 42000
    [1] => 1055
    [2] => Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'economizzer.y.hexcolor_category' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
)
 Caused by: PDOException
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'economizzer.y.hexcolor_category' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

in C:\WAMP\wamp64\www\economizzer\vendor\yiisoft\yii2\db\Command.php at line 902

Adrian

**Comment by gugoan** [comment]
I could not reproduce the error. I think the problem is related to **"Mysql - Enable/Disable ONLY_FULL_GROUP_BY"**.

See if these topics can help you:

[https://stackoverflow.com/questions/23921117/disable-only-full-group-by](https://stackoverflow.com/questions/23921117/disable-only-full-group-by)

[https://stackoverflow.com/questions/34115174/error-related-to-only-full-group-by-when-executing-a-query-in-mysql](https://stackoverflow.com/questions/34115174/error-related-to-only-full-group-by-when-executing-a-query-in-mysql)
