### ISSUE TITLE
economizzer on Docker and doesn't work db configuration

### ISSUE THREAD

**Issue by jsnpereira** [gugoan/economizzer#132]
Hi! I creating the dockerfile to run the economizzer.

I ran the mysql container IP is 172.17.0.4 and setup the IP on db.php file after that I added it on config folder, follow:
return [
    'class' => 'yii\db\Connection',
    'dsn' => 'mysql:host=172.17.0.4;dbname=economizzer',
    'username' => 'root',
    'password' => '@bcd1234',
    'charset' => 'utf8',
    'enableSchemaCache' => true,
];

So I just tried to access, typed the username and password on fields. but the page was showing:
SQLSTATE[HY000] [1044] Access denied for user 'root'@'172.17.0.2' to database 'economizzer'
Why is it another IP? You can see the print below.
![image](https://user-images.githubusercontent.com/6789768/42007024-e25ed9d2-7a53-11e8-9b5e-9c8f18c6ef5e.png)

I hope you can help about that.

Best regard,
Jeison Pereira

**Comment by jsnpereira** [comment]
@gugoan 
Please check the database config on PHP file, please!

Thanks,
Jeison Pereira

**Comment by gugoan** [comment]
Hello @jsnpereira ,
How strange to see another IP, well I'm not aware of working with "Docker" but I believe this problem is some specific issue of your environment.

The `host` parameter configured in `db.php` is where the system will fetch the database, even if the database server is different from where the files are.

Try performing a clean installation in another environment.
Any questions please let me know
